language: node_js
notifications:
  email: false
cache:
  directories:
    - node_modules
node_js:
  - "10"
  - "8"
jobs:
  include:
    - stage: test
      script: npm test
    - stage: release
      if: branch = master
      node_js: lts/*
      script:
        - npm run build
      deploy:
        provider: script
        skip_cleanup: true
        script: npx semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
